import { writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { UI_TOKENS } from '../data/ui/tokens';
import { TEAM_COLORS } from '../constants';
import { Team } from '../types';

export function generateTokensCss(): string {
    const lines: string[] = [
        '/**',
        ' * AUTO-GENERATED by tools/gen-ui-tokens.ts',
        ' * DO NOT EDIT MANUALLY. Update data/ui/tokens.ts and constants.ts instead.',
        ' */',
        ':root {',
    ];

    const toKebab = (str: string) => str.replace(/([a-z0-9]|(?=[A-Z]))([A-Z])/g, '$1-$2').toLowerCase();

    const flatten = (obj: Record<string, unknown>, prefix: string = '--token') => {
        for (const [key, value] of Object.entries(obj)) {
            const kebabKey = toKebab(key);
            const varName = key === 'DEFAULT' ? prefix : `${prefix}-${kebabKey}`;
            if (typeof value === 'object' && value !== null) {
                flatten(value as Record<string, unknown>, varName);
            } else if (typeof value === 'string') {
                lines.push(`  ${varName}: ${value};`);
            }
        }
    };

    flatten(UI_TOKENS);

    // Team metadata tokens (glow, border-radius) from TEAM_COLORS SSOT
    lines.push('');
    lines.push('  /* Team metadata from constants.ts TEAM_COLORS SSOT */');
    lines.push(`  --token-team-blue-glow: ${TEAM_COLORS[Team.BLUE].glow};`);
    lines.push(`  --token-team-blue-radius: ${TEAM_COLORS[Team.BLUE].borderRadius};`);
    lines.push(`  --token-team-red-glow: ${TEAM_COLORS[Team.RED].glow};`);
    lines.push(`  --token-team-red-radius: ${TEAM_COLORS[Team.RED].borderRadius};`);

    lines.push('}');
    lines.push('');
    return lines.join('\n');
}

const __filename = fileURLToPath(import.meta.url);
const outPath = resolve(dirname(__filename), '../styles/tokens.css');

export function writeTokensCss(): void {
    mkdirSync(dirname(outPath), { recursive: true });
    const content = generateTokensCss();
    writeFileSync(outPath, content, 'utf8');
    console.log(`PASS  Generated tokens at ${outPath}`);
}

if (!process.env.VITEST) {
    writeTokensCss();
}
